# Generated by Django 5.2.7 on 2025-10-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для заявок')),
                ('subject_template_ru', models.CharField(max_length=200, verbose_name='Тема письма (русский)')),
                ('subject_template_kg', models.CharField(max_length=200, verbose_name='Тема письма (кыргызский)')),
                ('subject_template_en', models.CharField(max_length=200, verbose_name='Тема письма (английский)')),
                ('deadline_text_ru', models.CharField(max_length=200, verbose_name='Текст дедлайна (русский)')),
                ('deadline_text_kg', models.CharField(max_length=200, verbose_name='Текст дедлайна (кыргызский)')),
                ('deadline_text_en', models.CharField(max_length=200, verbose_name='Текст дедлайна (английский)')),
                ('documents_ru', models.JSONField(default=list, verbose_name='Документы (русский)')),
                ('documents_kg', models.JSONField(default=list, verbose_name='Документы (кыргызский)')),
                ('documents_en', models.JSONField(default=list, verbose_name='Документы (английский)')),
            ],
            options={
                'verbose_name': 'Информация о подаче заявки',
                'verbose_name_plural': 'Информация о подаче заявки',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (кыргызский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=100, verbose_name='Цвет градиента')),
                ('bg_color', models.CharField(default='from-blue-50 to-cyan-50', max_length=100, verbose_name='Цвет фона')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория вакансий',
                'verbose_name_plural': 'Категории вакансий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Подпись (русский)')),
                ('label_kg', models.CharField(max_length=100, verbose_name='Подпись (кыргызский)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Подпись (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика вакансий',
                'verbose_name_plural': 'Статистика вакансий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Название (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('requirements_ru', models.JSONField(default=list, verbose_name='Требования (русский)')),
                ('requirements_kg', models.JSONField(default=list, verbose_name='Требования (кыргызский)')),
                ('requirements_en', models.JSONField(default=list, verbose_name='Требования (английский)')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Зарплата')),
                ('work_schedule', models.CharField(blank=True, max_length=100, verbose_name='График работы')),
                ('employment_type', models.CharField(blank=True, max_length=100, verbose_name='Тип занятости')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('closed', 'Закрытая'), ('draft', 'Черновик')], default='active', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='В избранное')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочная')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies_app.vacancycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
