# Generated by Django 5.2.7 on 2025-10-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Название (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('date', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('participants', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CouncilFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет иконки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Функция совета',
                'verbose_name_plural': 'Функции совета',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (кыргызский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (английский)')),
                ('position_ru', models.CharField(max_length=200, verbose_name='Должность (русский)')),
                ('position_kg', models.CharField(max_length=200, verbose_name='Должность (кыргызский)')),
                ('position_en', models.CharField(max_length=200, verbose_name='Должность (английский)')),
                ('bio_ru', models.TextField(verbose_name='Биография (русский)')),
                ('bio_kg', models.TextField(verbose_name='Биография (кыргызский)')),
                ('bio_en', models.TextField(verbose_name='Биография (английский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='council/members/', verbose_name='Фото')),
                ('position_type', models.CharField(choices=[('president', 'Президент'), ('vice_president', 'Вице-президент'), ('academic_manager', 'Академический менеджер'), ('event_manager', 'Менеджер мероприятий'), ('pr_manager', 'PR менеджер'), ('sports_manager', 'Спортивный менеджер'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип должности')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Член совета',
                'verbose_name_plural': 'Члены совета',
                'ordering': ['order', 'position_type'],
            },
        ),
        migrations.CreateModel(
            name='CouncilStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Подпись (русский)')),
                ('label_kg', models.CharField(max_length=100, verbose_name='Подпись (кыргызский)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Подпись (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
    ]
