# Generated by Django 5.2.7 on 2025-10-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер аудитории')),
                ('building', models.CharField(max_length=50, verbose_name='Корпус')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('room_type_ru', models.CharField(max_length=100, verbose_name='Тип аудитории (русский)')),
                ('room_type_kg', models.CharField(max_length=100, verbose_name='Тип аудитории (кыргызский)')),
                ('room_type_en', models.CharField(max_length=100, verbose_name='Тип аудитории (английский)')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название (русский)')),
                ('name_kg', models.CharField(max_length=50, verbose_name='Название (кыргызский)')),
                ('name_en', models.CharField(max_length=50, verbose_name='Название (английский)')),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=100, verbose_name='Цвет градиента')),
                ('short_name_ru', models.CharField(max_length=10, verbose_name='Короткое название (русский)')),
                ('short_name_kg', models.CharField(max_length=10, verbose_name='Короткое название (кыргызский)')),
                ('short_name_en', models.CharField(max_length=10, verbose_name='Короткое название (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет иконки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Особенность расписания',
                'verbose_name_plural': 'Особенности расписания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Подпись (русский)')),
                ('label_kg', models.CharField(max_length=100, verbose_name='Подпись (кыргызский)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Подпись (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика расписания',
                'verbose_name_plural': 'Статистика расписания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('full_name_ru', models.CharField(max_length=200, verbose_name='Полное название (русский)')),
                ('full_name_kg', models.CharField(max_length=200, verbose_name='Полное название (кыргызский)')),
                ('full_name_en', models.CharField(max_length=200, verbose_name='Полное название (английский)')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('department', models.CharField(max_length=100, verbose_name='Факультет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название (кыргызский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (английский)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код предмета')),
                ('credits', models.IntegerField(verbose_name='Кредиты')),
                ('hours_total', models.IntegerField(verbose_name='Всего часов')),
                ('hours_lecture', models.IntegerField(default=0, verbose_name='Лекционные часы')),
                ('hours_practice', models.IntegerField(default=0, verbose_name='Практические часы')),
                ('hours_lab', models.IntegerField(default=0, verbose_name='Лабораторные часы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='ФИО (русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='ФИО (кыргызский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='ФИО (английский)')),
                ('position_ru', models.CharField(max_length=100, verbose_name='Должность (русский)')),
                ('position_kg', models.CharField(max_length=100, verbose_name='Должность (кыргызский)')),
                ('position_en', models.CharField(max_length=100, verbose_name='Должность (английский)')),
                ('department', models.CharField(max_length=100, verbose_name='Кафедра')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер пары')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('week_type', models.CharField(choices=[('both', 'Обе недели'), ('numerator', 'Числитель'), ('denominator', 'Знаменатель')], default='both', max_length=15, verbose_name='Тип недели')),
                ('subgroup', models.CharField(blank=True, max_length=10, verbose_name='Подгруппа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.classroom', verbose_name='Аудитория')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.lessontype', verbose_name='Тип занятия')),
                ('groups', models.ManyToManyField(to='schedule_app.studygroup', verbose_name='Группы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.teacher', verbose_name='Преподаватель')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.timeslot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'time_slot__number', 'order'],
            },
        ),
    ]
