# Generated by Django 5.1.2 on 2025-11-01 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('course', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Курс')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (English)')),
                ('name_ky', models.CharField(max_length=200, verbose_name='Название (Кыргызча)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код предмета')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кредиты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Номер пары')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер аудитории')),
                ('building', models.CharField(max_length=50, verbose_name='Корпус')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('room_type', models.CharField(choices=[('lecture', 'Лекционная'), ('computer', 'Компьютерная'), ('lab', 'Лаборатория'), ('gym', 'Спортзал'), ('library', 'Библиотека'), ('conference', 'Конференц-зал'), ('other', 'Другое')], default='lecture', max_length=20, verbose_name='Тип аудитории')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['building', 'number'],
                'unique_together': {('number', 'building')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('department', models.CharField(max_length=200, verbose_name='Кафедра')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('subjects', models.ManyToManyField(to='schedule_app.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная'), ('seminar', 'Семинар'), ('exam', 'Экзамен'), ('module', 'Модуль'), ('consultation', 'Консультация'), ('project', 'Проектная работа'), ('elective', 'Элективный курс'), ('club', 'Кружок'), ('sports', 'Спорт')], default='lecture', max_length=20, verbose_name='Тип занятия')),
                ('week_type', models.CharField(choices=[('all', 'Каждую неделю'), ('odd', 'Нечетная неделя'), ('even', 'Четная неделя')], default='all', max_length=10, verbose_name='Тип недели')),
                ('start_date', models.DateField(default='2024-01-01', verbose_name='Дата начала')),
                ('end_date', models.DateField(default='2024-12-31', verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.room', verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.studygroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.teacher', verbose_name='Преподаватель')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.timeslot', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['weekday', 'time_slot__number'],
                'unique_together': {('group', 'weekday', 'time_slot', 'start_date', 'end_date'), ('room', 'weekday', 'time_slot', 'start_date', 'end_date'), ('teacher', 'weekday', 'time_slot', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('cancel', 'Отмена'), ('reschedule', 'Перенос'), ('substitute', 'Замена преподавателя'), ('room_change', 'Смена аудитории')], max_length=20, verbose_name='Тип изменения')),
                ('change_date', models.DateField(verbose_name='Дата изменения')),
                ('reason', models.TextField(verbose_name='Причина изменения')),
                ('created_by', models.CharField(max_length=100, verbose_name='Кем создано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.room', verbose_name='Новая аудитория')),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.schedule', verbose_name='Оригинальное расписание')),
                ('new_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.teacher', verbose_name='Новый преподаватель')),
                ('new_time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.timeslot', verbose_name='Новое время')),
            ],
            options={
                'verbose_name': 'Изменение расписания',
                'verbose_name_plural': 'Изменения расписания',
                'ordering': ['-created_at'],
            },
        ),
    ]
