# Generated by Django 5.1.2 on 2025-11-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'ordering': ['name'], 'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name_ru'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
    ]
