# Generated by Django 5.1.2 on 2025-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_alter_studygroup_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер аудитории'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
    ]
