# Generated by Django 5.1.2 on 2025-11-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_room_options_alter_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'weekday', 'time_slot', 'start_date', 'end_date'), ('teacher', 'weekday', 'time_slot', 'start_date', 'end_date')},
        ),
    ]
