# Generated by Django 5.1.2 on 2025-11-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'weekday', 'time_slot', 'start_date', 'end_date')},
        ),
    ]
