# Generated by Django 5.2.7 on 2025-10-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (кыргызский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (английский)')),
                ('subject_ru', models.CharField(max_length=200, verbose_name='Предмет (русский)')),
                ('subject_kg', models.CharField(max_length=200, verbose_name='Предмет (кыргызский)')),
                ('subject_en', models.CharField(max_length=200, verbose_name='Предмет (английский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото')),
                ('experience_ru', models.CharField(max_length=100, verbose_name='Опыт (русский)')),
                ('experience_kg', models.CharField(max_length=100, verbose_name='Опыт (кыргызский)')),
                ('experience_en', models.CharField(max_length=100, verbose_name='Опыт (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', help_text='Например: from-blue-500 to-cyan-500', max_length=100, verbose_name='Цвет градиента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Достижение (русский)')),
                ('text_kg', models.TextField(verbose_name='Достижение (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Достижение (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['order'],
            },
        ),
    ]
