# Generated by Django 5.2.7 on 2025-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация (временно)'),
        ),
    ]
