# Generated by Django 5.1.2 on 2025-10-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_fix_specialization_nullable'),
    ]

    operations = [
        # SQLite doesn't always properly alter columns, so we need to recreate the field
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(
                max_length=200,
                null=True,
                blank=True,
                verbose_name='Специализация (временно)',
            ),
        ),
    ]
