# Generated by Django 5.2.7 on 2025-10-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (кыргызский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (английский)')),
                ('excerpt_ru', models.TextField(max_length=500, verbose_name='Краткое описание (русский)')),
                ('excerpt_kg', models.TextField(max_length=500, verbose_name='Краткое описание (кыргызский)')),
                ('excerpt_en', models.TextField(max_length=500, verbose_name='Краткое описание (английский)')),
                ('content_ru', models.TextField(verbose_name='Полный текст (русский)')),
                ('content_kg', models.TextField(verbose_name='Полный текст (кыргызский)')),
                ('content_en', models.TextField(verbose_name='Полный текст (английский)')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Главное изображение')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/', verbose_name='Миниатюра')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_featured', models.BooleanField(default=False, verbose_name='В избранное')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Подпись (русский)')),
                ('caption_kg', models.CharField(blank=True, max_length=200, verbose_name='Подпись (кыргызский)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Подпись (английский)')),
                ('order', models.IntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_app.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
