# Generated by Django 5.1.2 on 2025-11-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
