# Generated by Django 5.2.7 on 2025-10-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет иконки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Функция библиотеки',
                'verbose_name_plural': 'Функции библиотеки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LibraryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Подпись (русский)')),
                ('label_kg', models.CharField(max_length=100, verbose_name='Подпись (кыргызский)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Подпись (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика библиотеки',
                'verbose_name_plural': 'Статистика библиотеки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (русский)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (кыргызский)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (английский)')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=100, verbose_name='Цвет градиента')),
                ('bg_color', models.CharField(default='from-blue-50 to-cyan-50', max_length=100, verbose_name='Цвет фона')),
                ('border_color', models.CharField(default='border-blue-200', max_length=100, verbose_name='Цвет бордера')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория ресурсов',
                'verbose_name_plural': 'Категории ресурсов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_ru', models.CharField(max_length=50, verbose_name='День (русский)')),
                ('day_kg', models.CharField(max_length=50, verbose_name='День (кыргызский)')),
                ('day_en', models.CharField(max_length=50, verbose_name='День (английский)')),
                ('time_ru', models.CharField(max_length=50, verbose_name='Время (русский)')),
                ('time_kg', models.CharField(max_length=50, verbose_name='Время (кыргызский)')),
                ('time_en', models.CharField(max_length=50, verbose_name='Время (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Часы работы',
                'verbose_name_plural': 'Часы работы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Название (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('resource_type', models.CharField(choices=[('paper', 'Бумажный'), ('electronic', 'Электронный'), ('mixed', 'Смешанный')], max_length=20, verbose_name='Тип ресурса')),
                ('access_type', models.CharField(choices=[('physical', 'Физический доступ'), ('online', 'Онлайн доступ'), ('campus', 'Доступ в кампусе'), ('subscription', 'По подписке')], max_length=20, verbose_name='Тип доступа')),
                ('count', models.CharField(max_length=50, verbose_name='Количество')),
                ('available_count', models.IntegerField(default=0, verbose_name='Доступное количество')),
                ('access_url', models.URLField(blank=True, verbose_name='Ссылка для доступа')),
                ('download_url', models.URLField(blank=True, verbose_name='Ссылка для скачивания')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='resources/documents/', verbose_name='Файл документа')),
                ('is_featured', models.BooleanField(default=False, verbose_name='В избранное')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources_app.resourcecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Образовательный ресурс',
                'verbose_name_plural': 'Образовательные ресурсы',
                'ordering': ['order', 'category__order'],
            },
        ),
    ]
