# Generated by Django 5.2.7 on 2025-10-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Подпись (русский)')),
                ('label_kg', models.CharField(max_length=100, verbose_name='Подпись (кыргызский)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Подпись (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика проектов',
                'verbose_name_plural': 'Статистика проектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_ru', models.CharField(max_length=200, verbose_name='Имя студента (русский)')),
                ('student_name_kg', models.CharField(max_length=200, verbose_name='Имя студента (кыргызский)')),
                ('student_name_en', models.CharField(max_length=200, verbose_name='Имя студента (английский)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название проекта (русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Название проекта (кыргызский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название проекта (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='projects/students/', verbose_name='Фото студента')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Скриншот проекта')),
                ('github_url', models.URLField(verbose_name='GitHub репозиторий')),
                ('website_url', models.URLField(blank=True, verbose_name='Вебсайт проекта')),
                ('demo_url', models.URLField(blank=True, verbose_name='Демо ссылка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='В избранное')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Студенческий проект',
                'verbose_name_plural': 'Студенческие проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название технологии')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=100, verbose_name='Цвет градиента')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects_app.studentproject')),
            ],
            options={
                'verbose_name': 'Технология проекта',
                'verbose_name_plural': 'Технологии проекта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=200, verbose_name='Особенность (русский)')),
                ('text_kg', models.CharField(max_length=200, verbose_name='Особенность (кыргызский)')),
                ('text_en', models.CharField(max_length=200, verbose_name='Особенность (английский)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects_app.studentproject')),
            ],
            options={
                'verbose_name': 'Особенность проекта',
                'verbose_name_plural': 'Особенности проекта',
                'ordering': ['order'],
            },
        ),
    ]
