# Generated by Django 5.2.7 on 2025-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Игнор'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/students/', verbose_name='Скриншот проекта'),
        ),
    ]
